"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
pwd = os.path.dirname(os.path.realpath(__file__))
from setuptools import setup

APP = ['Main.py']
DATA_FILES = [('', ['images','apk','platform-tools'])]
OPTIONS = {
    'iconfile': pwd+'icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
